[package]
name = "derive"
version = "0.1.0"
authors = ["Brett Etter <bbetter9101@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.17"
quote = "1.0.3"
